// Code generated by Basil. DO NOT EDIT.
package fixtures

import (
	"fmt"

	"github.com/opsidian/basil/basil"
)

type BlockWithBlockInterfaceInterpreter struct{}

// Create creates a new BlockWithBlockInterface block
func (i BlockWithBlockInterfaceInterpreter) CreateBlock(id basil.ID) basil.Block {
	return &BlockWithBlockInterface{
		IDField: id,
	}
}

// Params returns with the list of valid parameters
func (i BlockWithBlockInterfaceInterpreter) Params() map[basil.ID]basil.ParameterDescriptor {
	return nil
}

// HasForeignID returns true if the block ID is referencing an other block id
func (i BlockWithBlockInterfaceInterpreter) HasForeignID() bool {
	return false
}

// HasShortFormat returns true if the block can be defined in the short block format
func (i BlockWithBlockInterfaceInterpreter) ValueParamName() basil.ID {
	return ""
}

// ParseContext returns with the parse context for the block
func (i BlockWithBlockInterfaceInterpreter) ParseContext(ctx *basil.ParseContext) *basil.ParseContext {
	var nilBlock *BlockWithBlockInterface
	if b, ok := basil.Block(nilBlock).(basil.ParseContextOverrider); ok {
		return ctx.New(b.ParseContextOverride())
	}

	return ctx
}

func (i BlockWithBlockInterfaceInterpreter) Param(b basil.Block, name basil.ID) interface{} {
	switch name {
	case "id":
		return b.(*BlockWithBlockInterface).IDField
	default:
		panic(fmt.Errorf("unexpected parameter %q in BlockWithBlockInterface", name))
	}
}

func (i BlockWithBlockInterfaceInterpreter) SetParam(b basil.Block, name basil.ID, value interface{}) error {
	return nil
}

func (i BlockWithBlockInterfaceInterpreter) SetBlock(b basil.Block, name basil.ID, value interface{}) error {
	switch name {
	case "block_simple":
		b.(*BlockWithBlockInterface).Blocks = append(b.(*BlockWithBlockInterface).Blocks, value.(BlockInterface))
	}
	return nil
}
