// Code generated by Basil. DO NOT EDIT.

package fixtures

import (
	"fmt"

	"github.com/opsidian/conflow/basil"
	"github.com/opsidian/conflow/basil/schema"
)

// BlockSimpleInterpreter is the basil interpreter for the BlockSimple block
type BlockSimpleInterpreter struct {
	s schema.Schema
}

func (i BlockSimpleInterpreter) Schema() schema.Schema {
	if i.s == nil {
		i.s = &schema.Object{
			Name: "BlockSimple",
			Properties: map[string]schema.Schema{
				"id_field": &schema.String{
					Metadata: schema.Metadata{
						Annotations: map[string]string{"id": "true"},
						ReadOnly:    true,
					},
					Format: "basil.ID",
				},
				"value": &schema.String{
					Metadata: schema.Metadata{
						Annotations: map[string]string{"value": "true"},
					},
				},
			},
			PropertyNames: map[string]string{"id_field": "IDField", "value": "Value"},
		}
	}
	return i.s
}

// Create creates a new BlockSimple block
func (i BlockSimpleInterpreter) CreateBlock(id basil.ID, blockCtx *basil.BlockContext) basil.Block {
	return &BlockSimple{
		IDField: id,
	}
}

// ValueParamName returns the name of the parameter marked as value field, if there is one set
func (i BlockSimpleInterpreter) ValueParamName() basil.ID {
	return "value"
}

// ParseContext returns with the parse context for the block
func (i BlockSimpleInterpreter) ParseContext(ctx *basil.ParseContext) *basil.ParseContext {
	var nilBlock *BlockSimple
	if b, ok := basil.Block(nilBlock).(basil.ParseContextOverrider); ok {
		return ctx.New(b.ParseContextOverride())
	}

	return ctx
}

func (i BlockSimpleInterpreter) Param(b basil.Block, name basil.ID) interface{} {
	switch name {
	case "id_field":
		return b.(*BlockSimple).IDField
	case "value":
		return b.(*BlockSimple).Value
	default:
		panic(fmt.Errorf("unexpected parameter %q in BlockSimple", name))
	}
}

func (i BlockSimpleInterpreter) SetParam(block basil.Block, name basil.ID, value interface{}) error {
	b := block.(*BlockSimple)
	switch name {
	case "value":
		b.Value = value.(string)
	}
	return nil
}

func (i BlockSimpleInterpreter) SetBlock(block basil.Block, name basil.ID, value interface{}) error {
	return nil
}
