// Code generated by Basil. DO NOT EDIT.
package fixtures

import (
	"fmt"

	"github.com/opsidian/basil/basil"
)

type BlockWithReferenceInterpreter struct{}

// Create creates a new BlockWithReference block
func (i BlockWithReferenceInterpreter) CreateBlock(id basil.ID) basil.Block {
	return &BlockWithReference{
		IDField: id,
	}
}

// Params returns with the list of valid parameters
func (i BlockWithReferenceInterpreter) Params() map[basil.ID]basil.ParameterDescriptor {
	return nil
}

// HasForeignID returns true if the block ID is referencing an other block id
func (i BlockWithReferenceInterpreter) HasForeignID() bool {
	return true
}

// HasShortFormat returns true if the block can be defined in the short block format
func (i BlockWithReferenceInterpreter) ValueParamName() basil.ID {
	return ""
}

// ParseContext returns with the parse context for the block
func (i BlockWithReferenceInterpreter) ParseContext(ctx *basil.ParseContext) *basil.ParseContext {
	var nilBlock *BlockWithReference
	if b, ok := basil.Block(nilBlock).(basil.ParseContextOverrider); ok {
		return ctx.New(b.ParseContextOverride())
	}

	return ctx
}

func (i BlockWithReferenceInterpreter) Param(b basil.Block, name basil.ID) interface{} {
	switch name {
	case "id":
		return b.(*BlockWithReference).IDField
	default:
		panic(fmt.Errorf("unexpected parameter %q in BlockWithReference", name))
	}
}

func (i BlockWithReferenceInterpreter) SetParam(b basil.Block, name basil.ID, value interface{}) error {
	return nil
}

func (i BlockWithReferenceInterpreter) SetBlock(b basil.Block, name basil.ID, value interface{}) error {
	return nil
}
