// Code generated by Basil. DO NOT EDIT.

package fixtures

import (
	"fmt"
	"github.com/opsidian/basil/basil"
	"github.com/opsidian/basil/basil/schema"
)

// BlockWithInterfaceInterpreter is the basil interpreter for the BlockWithInterface block
type BlockWithInterfaceInterpreter struct {
	s schema.Schema
}

func (i BlockWithInterfaceInterpreter) Schema() schema.Schema {
	if i.s == nil {
		i.s = &schema.Object{
			Name: "BlockWithInterface",
			Properties: map[string]schema.Schema{
				"block": &schema.Reference{
					Ref: "http://basil.schema/github.com/opsidian/basil/basil.Block",
				},
				"blocks": &schema.Array{
					Items: &schema.Reference{
						Ref: "http://basil.schema/github.com/opsidian/basil/basil.Block",
					},
				},
				"id_field": &schema.String{
					Metadata: schema.Metadata{
						Annotations: map[string]string{"id": "true"},
						ReadOnly:    true,
					},
					Format: "basil.ID",
				},
			},
			PropertyNames: map[string]string{"block": "Block", "blocks": "Blocks", "id_field": "IDField"},
		}
	}
	return i.s
}

// Create creates a new BlockWithInterface block
func (i BlockWithInterfaceInterpreter) CreateBlock(id basil.ID, blockCtx *basil.BlockContext) basil.Block {
	return &BlockWithInterface{
		IDField: id,
	}
}

// ValueParamName returns the name of the parameter marked as value field, if there is one set
func (i BlockWithInterfaceInterpreter) ValueParamName() basil.ID {
	return ""
}

// ParseContext returns with the parse context for the block
func (i BlockWithInterfaceInterpreter) ParseContext(ctx *basil.ParseContext) *basil.ParseContext {
	var nilBlock *BlockWithInterface
	if b, ok := basil.Block(nilBlock).(basil.ParseContextOverrider); ok {
		return ctx.New(b.ParseContextOverride())
	}

	return ctx
}

func (i BlockWithInterfaceInterpreter) Param(b basil.Block, name basil.ID) interface{} {
	switch name {
	case "id_field":
		return b.(*BlockWithInterface).IDField
	default:
		panic(fmt.Errorf("unexpected parameter %q in BlockWithInterface", name))
	}
}

func (i BlockWithInterfaceInterpreter) SetParam(block basil.Block, name basil.ID, value interface{}) error {
	return nil
}

func (i BlockWithInterfaceInterpreter) SetBlock(block basil.Block, name basil.ID, value interface{}) error {
	b := block.(*BlockWithInterface)
	switch name {
	case "block":
		b.Block = value.(basil.Block)
	case "blocks":
		b.Blocks = append(b.Blocks, value.(basil.Block))
	}
	return nil
}
