// Code generated by Conflow. DO NOT EDIT.

package schema

import (
	"github.com/conflowio/conflow/pkg/conflow/annotations"
)

func init() {
	Register(&Object{
		Metadata: Metadata{
			Annotations: map[string]string{
				annotations.Type: "configuration",
			},
			ID: "github.com/conflowio/conflow/pkg/schema.Any",
		},
		FieldNames:     map[string]string{"$id": "ID", "const": "Const", "default": "Default", "deprecated": "Deprecated", "description": "Description", "enum": "Enum", "examples": "Examples", "nullable": "Nullable", "readOnly": "ReadOnly", "title": "Title", "writeOnly": "WriteOnly", "x-annotations": "Annotations"},
		ParameterNames: map[string]string{"$id": "id", "readOnly": "read_only", "writeOnly": "write_only", "x-annotations": "annotations"},
		Properties: map[string]Schema{
			"$id":         &String{},
			"const":       &Any{},
			"default":     &Any{},
			"deprecated":  &Boolean{},
			"description": &String{},
			"enum": &Array{
				Items: &Any{},
			},
			"examples": &Array{
				Items: &Any{},
			},
			"nullable":  &Boolean{},
			"readOnly":  &Boolean{},
			"title":     &String{},
			"writeOnly": &Boolean{},
			"x-annotations": &Map{
				AdditionalProperties: &String{},
			},
		},
	})
}

// NewAnyWithDefaults creates a new Any instance with default values
func NewAnyWithDefaults() *Any {
	b := &Any{}
	return b
}
