// Code generated by Conflow. DO NOT EDIT.

package schema

import (
	"github.com/conflowio/conflow/pkg/conflow/annotations"
)

func init() {
	Register(&Object{
		Metadata: Metadata{
			Annotations: map[string]string{
				annotations.Type: "configuration",
			},
			ID: "github.com/conflowio/conflow/pkg/schema.Reference",
		},
		FieldNames:     map[string]string{"$id": "ID", "$ref": "Ref", "deprecated": "Deprecated", "description": "Description", "examples": "Examples", "nullable": "Nullable", "readOnly": "ReadOnly", "title": "Title", "writeOnly": "WriteOnly", "x-annotations": "Annotations"},
		ParameterNames: map[string]string{"$id": "id", "$ref": "ref", "readOnly": "read_only", "writeOnly": "write_only", "x-annotations": "annotations"},
		Properties: map[string]Schema{
			"$id": &String{},
			"$ref": &String{
				Metadata: Metadata{
					Annotations: map[string]string{
						annotations.Value: "true",
					},
				},
			},
			"deprecated":  &Boolean{},
			"description": &String{},
			"examples": &Array{
				Items: &Any{},
			},
			"nullable":  &Boolean{},
			"readOnly":  &Boolean{},
			"title":     &String{},
			"writeOnly": &Boolean{},
			"x-annotations": &Map{
				AdditionalProperties: &String{},
			},
		},
		Required: []string{"ref"},
	})
}

// NewReferenceWithDefaults creates a new Reference instance with default values
func NewReferenceWithDefaults() *Reference {
	b := &Reference{}
	return b
}
