// Code generated by Conflow. DO NOT EDIT.

package test

import (
	"github.com/conflowio/conflow/src/schema"
)

// TestFunc2Interpreter is the conflow interpreter for the testFunc2 function
type TestFunc2Interpreter struct {
	s schema.Schema
}

func (i TestFunc2Interpreter) Schema() schema.Schema {
	if i.s == nil {
		i.s = &schema.Function{
			Parameters: schema.Parameters{
				schema.NamedSchema{
					Name:   "str1",
					Schema: &schema.String{},
				},
				schema.NamedSchema{
					Name:   "str2",
					Schema: &schema.String{},
				},
			},
			Result: &schema.String{},
		}
	}
	return i.s
}

// Eval returns with the result of the function
func (i TestFunc2Interpreter) Eval(ctx interface{}, args []interface{}) (interface{}, error) {
	var val0 = args[0].(string)
	var val1 = args[1].(string)
	return testFunc2(val0, val1), nil
}
