// Code generated by Basil. DO NOT EDIT.
package main

import (
	"fmt"

	"github.com/opsidian/basil/basil"
	"github.com/opsidian/basil/basil/variable"
)

type FileInterpreter struct{}

// Create creates a new File block
func (i FileInterpreter) CreateBlock(id basil.ID) basil.Block {
	return &File{
		id: id,
	}
}

// Params returns with the list of valid parameters
func (i FileInterpreter) Params() map[basil.ID]basil.ParameterDescriptor {
	return map[basil.ID]basil.ParameterDescriptor{
		"path": {
			Type:       "string",
			EvalStage:  basil.EvalStages["main"],
			IsRequired: false,
			IsOutput:   false,
		},
	}
}

// Blocks returns with the list of valid blocks
func (i FileInterpreter) Blocks() map[basil.ID]basil.BlockDescriptor {
	return nil
}

// HasForeignID returns true if the block ID is referencing an other block id
func (i FileInterpreter) HasForeignID() bool {
	return false
}

// HasShortFormat returns true if the block can be defined in the short block format
func (i FileInterpreter) ValueParamName() basil.ID {
	return ""
}

// ParseContext returns with the parse context for the block
func (i FileInterpreter) ParseContext(ctx *basil.ParseContext) *basil.ParseContext {
	var nilBlock *File
	if b, ok := basil.Block(nilBlock).(basil.ParseContextOverrider); ok {
		return ctx.New(b.ParseContextOverride())
	}

	return ctx
}

func (i FileInterpreter) Param(b basil.Block, name basil.ID) interface{} {
	switch name {
	case "id":
		return b.(*File).id
	case "path":
		return b.(*File).path
	default:
		panic(fmt.Errorf("unexpected parameter %q in File", name))
	}
}

func (i FileInterpreter) SetParam(block basil.Block, name basil.ID, value interface{}) error {
	var err error
	b := block.(*File)
	switch name {
	case "id":
		b.id, err = variable.IdentifierValue(value)
	case "path":
		b.path, err = variable.StringValue(value)
	}
	return err
}

func (i FileInterpreter) SetBlock(block basil.Block, name basil.ID, value interface{}) error {
	return nil
}
