// Code generated by Basil. DO NOT EDIT.

package directives

import (
	"fmt"

	"github.com/opsidian/basil/basil"
	"github.com/opsidian/basil/basil/schema"
)

// DescriptionInterpreter is the basil interpreter for the Description block
type DescriptionInterpreter struct {
	s schema.Schema
}

func (i DescriptionInterpreter) Schema() schema.Schema {
	if i.s == nil {
		i.s = &schema.Object{
			Properties: map[string]schema.Schema{
				"id": &schema.String{
					Metadata: schema.Metadata{
						Annotations: map[string]string{"id": "true"},
						ReadOnly:    true,
					},
					Format: "basil.ID",
				},
				"value": &schema.String{
					Metadata: schema.Metadata{
						Annotations: map[string]string{"value": "true"},
					},
				},
			},
			Required: []string{"value"},
		}
	}
	return i.s
}

// Create creates a new Description block
func (i DescriptionInterpreter) CreateBlock(id basil.ID) basil.Block {
	return &Description{
		id: id,
	}
}

func (i DescriptionInterpreter) Params() map[basil.ID]basil.ParameterDescriptor {
	return nil
}

func (i DescriptionInterpreter) Blocks() map[basil.ID]basil.BlockDescriptor {
	return nil
}

func (i DescriptionInterpreter) HasForeignID() bool {
	return false
}

// ValueParamName returns the name of the parameter marked as value field, if there is one set
func (i DescriptionInterpreter) ValueParamName() basil.ID {
	return "value"
}

// ParseContext returns with the parse context for the block
func (i DescriptionInterpreter) ParseContext(ctx *basil.ParseContext) *basil.ParseContext {
	var nilBlock *Description
	if b, ok := basil.Block(nilBlock).(basil.ParseContextOverrider); ok {
		return ctx.New(b.ParseContextOverride())
	}

	return ctx
}

func (i DescriptionInterpreter) Param(b basil.Block, name basil.ID) interface{} {
	switch name {
	case "id":
		return b.(*Description).id
	case "value":
		return b.(*Description).value
	default:
		panic(fmt.Errorf("unexpected parameter %q in Description", name))
	}
}

func (i DescriptionInterpreter) SetParam(block basil.Block, name basil.ID, value interface{}) error {
	b := block.(*Description)
	switch name {
	case "value":
		b.value = value.(string)
	}
	return nil
}

func (i DescriptionInterpreter) SetBlock(block basil.Block, name basil.ID, value interface{}) error {
	return nil
}

func (i DescriptionInterpreter) EvalStage() basil.EvalStage {
	var nilBlock *Description
	if b, ok := basil.Block(nilBlock).(basil.EvalStageAware); ok {
		return b.EvalStage()
	}

	return basil.EvalStageUndefined
}
