.PHONY: json
json:
	@go run ../../cmd/conflow/main.go openapi generate json

.PHONY: json-compact
json-compact:
	@go run ../../cmd/conflow/main.go openapi generate json --compact

.PHONY: yaml
yaml:
	@go run ../../cmd/conflow/main.go openapi generate yaml
