.PHONY: json
json:
	@conflow openapi generate --format json

.PHONY: json-compact
json-compact:
	@conflow openapi generate --format json --compact

.PHONY: yaml
yaml:
	@conflow openapi generate --format yaml
