// Code generated by Basil. DO NOT EDIT.

package blocks

import (
	"fmt"

	"github.com/opsidian/basil/basil"
	"github.com/opsidian/basil/basil/schema"
)

// RangeEntryInterpreter is the basil interpreter for the RangeEntry block
type RangeEntryInterpreter struct {
	s schema.Schema
}

func (i RangeEntryInterpreter) Schema() schema.Schema {
	if i.s == nil {
		i.s = &schema.Object{
			Properties: map[string]schema.Schema{
				"id": &schema.String{
					Metadata: schema.Metadata{
						Annotations: map[string]string{"id": "true"},
						ReadOnly:    true,
					},
					Format: "basil.ID",
				},
				"key": &schema.Untyped{
					Metadata: schema.Metadata{
						Annotations: map[string]string{"eval_stage": "close"},
						ReadOnly:    true,
					},
				},
				"value": &schema.Untyped{
					Metadata: schema.Metadata{
						Annotations: map[string]string{"eval_stage": "close"},
						ReadOnly:    true,
					},
				},
			},
		}
	}
	return i.s
}

// Create creates a new RangeEntry block
func (i RangeEntryInterpreter) CreateBlock(id basil.ID) basil.Block {
	return &RangeEntry{
		id: id,
	}
}

// ValueParamName returns the name of the parameter marked as value field, if there is one set
func (i RangeEntryInterpreter) ValueParamName() basil.ID {
	return ""
}

// ParseContext returns with the parse context for the block
func (i RangeEntryInterpreter) ParseContext(ctx *basil.ParseContext) *basil.ParseContext {
	var nilBlock *RangeEntry
	if b, ok := basil.Block(nilBlock).(basil.ParseContextOverrider); ok {
		return ctx.New(b.ParseContextOverride())
	}

	return ctx
}

func (i RangeEntryInterpreter) Param(b basil.Block, name basil.ID) interface{} {
	switch name {
	case "id":
		return b.(*RangeEntry).id
	case "key":
		return b.(*RangeEntry).key
	case "value":
		return b.(*RangeEntry).value
	default:
		panic(fmt.Errorf("unexpected parameter %q in RangeEntry", name))
	}
}

func (i RangeEntryInterpreter) SetParam(block basil.Block, name basil.ID, value interface{}) error {
	return nil
}

func (i RangeEntryInterpreter) SetBlock(block basil.Block, name basil.ID, value interface{}) error {
	return nil
}
