// Code generated by Basil. DO NOT EDIT.
package blocks

import (
	"fmt"

	"github.com/opsidian/basil/basil"
	"github.com/opsidian/basil/basil/variable"
)

type RangeInterpreter struct{}

// Create creates a new Range block
func (i RangeInterpreter) CreateBlock(id basil.ID) basil.Block {
	return &Range{
		id: id,
	}
}

// Params returns with the list of valid parameters
func (i RangeInterpreter) Params() map[basil.ID]basil.ParameterDescriptor {
	return map[basil.ID]basil.ParameterDescriptor{
		"value": {
			Type:       "interface{}",
			EvalStage:  basil.EvalStages["main"],
			IsRequired: false,
			IsOutput:   false,
		},
	}
}

// Blocks returns with the list of valid blocks
func (i RangeInterpreter) Blocks() map[basil.ID]basil.BlockDescriptor {
	return map[basil.ID]basil.BlockDescriptor{
		"entry": {
			EvalStage:   basil.EvalStages["init"],
			IsGenerated: true,
			IsRequired:  true,
			IsMany:      false,
		},
	}
}

// HasForeignID returns true if the block ID is referencing an other block id
func (i RangeInterpreter) HasForeignID() bool {
	return false
}

// HasShortFormat returns true if the block can be defined in the short block format
func (i RangeInterpreter) ValueParamName() basil.ID {
	return ""
}

// ParseContext returns with the parse context for the block
func (i RangeInterpreter) ParseContext(ctx *basil.ParseContext) *basil.ParseContext {
	var nilBlock *Range
	if b, ok := basil.Block(nilBlock).(basil.ParseContextOverrider); ok {
		return ctx.New(b.ParseContextOverride())
	}

	return ctx
}

func (i RangeInterpreter) Param(b basil.Block, name basil.ID) interface{} {
	switch name {
	case "id":
		return b.(*Range).id
	case "value":
		return b.(*Range).value
	default:
		panic(fmt.Errorf("unexpected parameter %q in Range", name))
	}
}

func (i RangeInterpreter) SetParam(block basil.Block, name basil.ID, value interface{}) error {
	var err error
	b := block.(*Range)
	switch name {
	case "id":
		b.id, err = variable.IdentifierValue(value)
	case "value":
		b.value, err = variable.AnyValue(value)
	}
	return err
}

func (i RangeInterpreter) SetBlock(block basil.Block, name basil.ID, value interface{}) error {
	b := block.(*Range)
	switch name {
	case "entry":
		b.entry = value.(*RangeEntry)
	}
	return nil
}
