// Code generated by Basil. DO NOT EDIT.

package blocks

import (
	"fmt"
	"github.com/opsidian/basil/basil"
	"github.com/opsidian/basil/basil/schema"
)

// RangeInterpreter is the basil interpreter for the Range block
type RangeInterpreter struct {
	s schema.Schema
}

func (i RangeInterpreter) Schema() schema.Schema {
	if i.s == nil {
		i.s = &schema.Object{
			Name: "Range",
			Properties: map[string]schema.Schema{
				"entry": &schema.Reference{
					Metadata: schema.Metadata{
						Annotations: map[string]string{"eval_stage": "init", "generated": "true"},
						Pointer:     true,
					},
					Ref: "http://basil.schema/github.com/opsidian/basil/blocks.RangeEntry",
				},
				"id": &schema.String{
					Metadata: schema.Metadata{
						Annotations: map[string]string{"id": "true"},
						ReadOnly:    true,
					},
					Format: "basil.ID",
				},
				"value": &schema.Untyped{},
			},
			Required: []string{"entry"},
		}
	}
	return i.s
}

// Create creates a new Range block
func (i RangeInterpreter) CreateBlock(id basil.ID, blockCtx *basil.BlockContext) basil.Block {
	return &Range{
		id:             id,
		blockPublisher: blockCtx.BlockPublisher(),
	}
}

// ValueParamName returns the name of the parameter marked as value field, if there is one set
func (i RangeInterpreter) ValueParamName() basil.ID {
	return ""
}

// ParseContext returns with the parse context for the block
func (i RangeInterpreter) ParseContext(ctx *basil.ParseContext) *basil.ParseContext {
	var nilBlock *Range
	if b, ok := basil.Block(nilBlock).(basil.ParseContextOverrider); ok {
		return ctx.New(b.ParseContextOverride())
	}

	return ctx
}

func (i RangeInterpreter) Param(b basil.Block, name basil.ID) interface{} {
	switch name {
	case "id":
		return b.(*Range).id
	case "value":
		return b.(*Range).value
	default:
		panic(fmt.Errorf("unexpected parameter %q in Range", name))
	}
}

func (i RangeInterpreter) SetParam(block basil.Block, name basil.ID, value interface{}) error {
	b := block.(*Range)
	switch name {
	case "value":
		b.value = value
	}
	return nil
}

func (i RangeInterpreter) SetBlock(block basil.Block, name basil.ID, value interface{}) error {
	b := block.(*Range)
	switch name {
	case "entry":
		b.entry = value.(*RangeEntry)
	}
	return nil
}
