// Code generated by Basil. DO NOT EDIT.
package blocks

import (
	"fmt"

	"github.com/opsidian/basil/basil"
	"github.com/opsidian/basil/basil/variable"
)

type SleepInterpreter struct{}

// Create creates a new Sleep block
func (i SleepInterpreter) CreateBlock(id basil.ID) basil.Block {
	return &Sleep{
		id: id,
	}
}

// Params returns with the list of valid parameters
func (i SleepInterpreter) Params() map[basil.ID]basil.ParameterDescriptor {
	return map[basil.ID]basil.ParameterDescriptor{
		"duration": {
			Type:       "time.Duration",
			EvalStage:  basil.EvalStages["main"],
			IsRequired: true,
			IsOutput:   false,
		},
	}
}

// Blocks returns with the list of valid blocks
func (i SleepInterpreter) Blocks() map[basil.ID]basil.BlockDescriptor {
	return nil
}

// HasForeignID returns true if the block ID is referencing an other block id
func (i SleepInterpreter) HasForeignID() bool {
	return false
}

// HasShortFormat returns true if the block can be defined in the short block format
func (i SleepInterpreter) ValueParamName() basil.ID {
	return ""
}

// ParseContext returns with the parse context for the block
func (i SleepInterpreter) ParseContext(ctx *basil.ParseContext) *basil.ParseContext {
	var nilBlock *Sleep
	if b, ok := basil.Block(nilBlock).(basil.ParseContextOverrider); ok {
		return ctx.New(b.ParseContextOverride())
	}

	return ctx
}

func (i SleepInterpreter) Param(b basil.Block, name basil.ID) interface{} {
	switch name {
	case "id":
		return b.(*Sleep).id
	case "duration":
		return b.(*Sleep).duration
	default:
		panic(fmt.Errorf("unexpected parameter %q in Sleep", name))
	}
}

func (i SleepInterpreter) SetParam(block basil.Block, name basil.ID, value interface{}) error {
	var err error
	b := block.(*Sleep)
	switch name {
	case "id":
		b.id, err = variable.IdentifierValue(value)
	case "duration":
		b.duration, err = variable.TimeDurationValue(value)
	}
	return err
}

func (i SleepInterpreter) SetBlock(block basil.Block, name basil.ID, value interface{}) error {
	return nil
}
