// Code generated by Conflow. DO NOT EDIT.

package blocks

import (
	"fmt"
	"github.com/conflowio/conflow/conflow"
	"github.com/conflowio/conflow/conflow/schema"
)

// TickInterpreter is the conflow interpreter for the Tick block
type TickInterpreter struct {
	s schema.Schema
}

func (i TickInterpreter) Schema() schema.Schema {
	if i.s == nil {
		i.s = &schema.Object{
			Name: "Tick",
			Parameters: map[string]schema.Schema{
				"id": &schema.String{
					Metadata: schema.Metadata{
						Annotations: map[string]string{"block.conflow.io/id": "true"},
						ReadOnly:    true,
					},
					Format: "conflow.ID",
				},
				"time": &schema.Time{
					Metadata: schema.Metadata{
						Annotations: map[string]string{"block.conflow.io/eval_stage": "close"},
						ReadOnly:    true,
					},
				},
			},
		}
	}
	return i.s
}

// Create creates a new Tick block
func (i TickInterpreter) CreateBlock(id conflow.ID, blockCtx *conflow.BlockContext) conflow.Block {
	return &Tick{
		id: id,
	}
}

// ValueParamName returns the name of the parameter marked as value field, if there is one set
func (i TickInterpreter) ValueParamName() conflow.ID {
	return ""
}

// ParseContext returns with the parse context for the block
func (i TickInterpreter) ParseContext(ctx *conflow.ParseContext) *conflow.ParseContext {
	var nilBlock *Tick
	if b, ok := conflow.Block(nilBlock).(conflow.ParseContextOverrider); ok {
		return ctx.New(b.ParseContextOverride())
	}

	return ctx
}

func (i TickInterpreter) Param(b conflow.Block, name conflow.ID) interface{} {
	switch name {
	case "id":
		return b.(*Tick).id
	case "time":
		return b.(*Tick).time
	default:
		panic(fmt.Errorf("unexpected parameter %q in Tick", name))
	}
}

func (i TickInterpreter) SetParam(block conflow.Block, name conflow.ID, value interface{}) error {
	return nil
}

func (i TickInterpreter) SetBlock(block conflow.Block, name conflow.ID, value interface{}) error {
	return nil
}
