// Code generated by Conflow. DO NOT EDIT.

package math

import (
	"github.com/conflowio/conflow/src/schema"
)

// CeilInterpreter is the conflow interpreter for the Ceil function
type CeilInterpreter struct {
	s schema.Schema
}

func (i CeilInterpreter) Schema() schema.Schema {
	if i.s == nil {
		i.s = &schema.Function{
			Metadata: schema.Metadata{
				Description: "It returns the least integer value greater than or equal to x.",
			},
			Parameters: schema.Parameters{
				schema.NamedSchema{
					Name: "number",
					Schema: &schema.Untyped{
						Types: []string{"integer", "number"},
					},
				},
			},
			Result: &schema.Integer{},
		}
	}
	return i.s
}

// Eval returns with the result of the function
func (i CeilInterpreter) Eval(ctx interface{}, args []interface{}) (interface{}, error) {
	var val0 = args[0]
	return Ceil(val0), nil
}
