// Code generated by Conflow. DO NOT EDIT.

package math

import (
	"github.com/conflowio/conflow/src/schema"
)

func init() {
	schema.Register(&schema.Function{
		Metadata: schema.Metadata{
			Description: "It returns with the greatest value",
			ID:          "github.com/conflowio/conflow/src/functions/math.Max",
		},
		AdditionalParameters: &schema.NamedSchema{
			Name: "rest",
			Schema: &schema.Any{
				Types: []string{"integer", "number"},
			},
		},
		Parameters: schema.Parameters{
			schema.NamedSchema{
				Name: "max",
				Schema: &schema.Any{
					Types: []string{"integer", "number"},
				},
			},
		},
		Result: &schema.Number{},
	})
}

// MaxInterpreter is the Conflow interpreter for the Max function
type MaxInterpreter struct {
}

func (i MaxInterpreter) Schema() schema.Schema {
	s, _ := schema.Get("github.com/conflowio/conflow/src/functions/math.Max")
	return s
}

// Eval returns with the result of the function
func (i MaxInterpreter) Eval(ctx interface{}, args []interface{}) (interface{}, error) {
	var val0 = args[0]
	var variadicArgs []interface{}
	for p := 1; p < len(args); p++ {
		var val = args[p]
		variadicArgs = append(variadicArgs, val)
	}
	return Max(val0, variadicArgs...), nil
}
