version: 2.1

workflows:
  version: 2
  main:
    jobs:
      - test
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

jobs:
  test:
    docker:
      - image: cimg/go:1.19
    working_directory: /home/circleci/go/src/github.com/conflowio/conflow
    resource_class: large
    steps:
      - checkout
      - run: make check
      - run: make test

  release:
    docker:
      - image: cimg/go:1.19
    resource_class: large
    steps:
      - checkout
      - run: go install github.com/goreleaser/goreleaser@latest
      - run: goreleaser
