version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/opsidian/basil
    steps:
      - checkout
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash)
