version: 2
jobs:
  test:
    docker:
      - image: cimg/go:1.19
    working_directory: /home/circleci/go/src/github.com/conflowio/conflow
    steps:
      - checkout
      - run: make check
      - run: make test

workflows:
  version: 2
  test:
    jobs:
      - test
