// Code generated by Basil. DO NOT EDIT.

package directives

import (
	"fmt"
	"github.com/opsidian/basil/basil"
	"github.com/opsidian/basil/basil/schema"
	"time"
)

// TimeoutInterpreter is the basil interpreter for the Timeout block
type TimeoutInterpreter struct {
	s schema.Schema
}

func (i TimeoutInterpreter) Schema() schema.Schema {
	if i.s == nil {
		i.s = &schema.Object{
			Metadata: schema.Metadata{
				Annotations: map[string]string{"eval_stage": "init"},
			},
			Properties: map[string]schema.Schema{
				"duration": &schema.TimeDuration{
					Metadata: schema.Metadata{
						Annotations: map[string]string{"value": "true"},
					},
				},
				"id": &schema.String{
					Metadata: schema.Metadata{
						Annotations: map[string]string{"id": "true"},
						ReadOnly:    true,
					},
					Format: "basil.ID",
				},
			},
			Required: []string{"duration"},
		}
	}
	return i.s
}

// Create creates a new Timeout block
func (i TimeoutInterpreter) CreateBlock(id basil.ID) basil.Block {
	return &Timeout{
		id: id,
	}
}

// ValueParamName returns the name of the parameter marked as value field, if there is one set
func (i TimeoutInterpreter) ValueParamName() basil.ID {
	return "duration"
}

// ParseContext returns with the parse context for the block
func (i TimeoutInterpreter) ParseContext(ctx *basil.ParseContext) *basil.ParseContext {
	var nilBlock *Timeout
	if b, ok := basil.Block(nilBlock).(basil.ParseContextOverrider); ok {
		return ctx.New(b.ParseContextOverride())
	}

	return ctx
}

func (i TimeoutInterpreter) Param(b basil.Block, name basil.ID) interface{} {
	switch name {
	case "duration":
		return b.(*Timeout).duration
	case "id":
		return b.(*Timeout).id
	default:
		panic(fmt.Errorf("unexpected parameter %q in Timeout", name))
	}
}

func (i TimeoutInterpreter) SetParam(block basil.Block, name basil.ID, value interface{}) error {
	b := block.(*Timeout)
	switch name {
	case "duration":
		b.duration = value.(time.Duration)
	}
	return nil
}

func (i TimeoutInterpreter) SetBlock(block basil.Block, name basil.ID, value interface{}) error {
	return nil
}
