// Code generated by Basil. DO NOT EDIT.
package common

import (
	"fmt"

	"github.com/opsidian/basil/basil"
	"github.com/opsidian/basil/basil/variable"
)

type PrintInterpreter struct{}

// Create creates a new Print block
func (i PrintInterpreter) CreateBlock(id basil.ID) basil.Block {
	return &Print{
		id: id,
	}
}

// Params returns with the list of valid parameters
func (i PrintInterpreter) Params() map[basil.ID]basil.ParameterDescriptor {
	return map[basil.ID]basil.ParameterDescriptor{
		"value":   {Type: "interface{}", IsRequired: true, IsOutput: false},
		"newline": {Type: "bool", IsRequired: false, IsOutput: false},
	}
}

// HasForeignID returns true if the block ID is referencing an other block id
func (i PrintInterpreter) HasForeignID() bool {
	return false
}

// HasShortFormat returns true if the block can be defined in the short block format
func (i PrintInterpreter) ValueParamName() basil.ID {
	return "value"
}

// ParseContext returns with the parse context for the block
func (i PrintInterpreter) ParseContext(ctx *basil.ParseContext) *basil.ParseContext {
	var nilBlock *Print
	if b, ok := basil.Block(nilBlock).(basil.ParseContextOverrider); ok {
		return ctx.New(b.ParseContextOverride())
	}

	return ctx
}

func (i PrintInterpreter) Param(b basil.Block, name basil.ID) interface{} {
	switch name {
	case "id":
		return b.(*Print).id
	case "value":
		return b.(*Print).value
	case "newline":
		return b.(*Print).newline
	default:
		panic(fmt.Errorf("unexpected parameter %q in Print", name))
	}
}

func (i PrintInterpreter) SetParam(b basil.Block, name basil.ID, value interface{}) error {
	var err error
	switch name {
	case "value":
		b.(*Print).value, err = variable.AnyValue(value)
	case "newline":
		b.(*Print).newline, err = variable.BoolValue(value)
	}
	return err
}

func (i PrintInterpreter) SetBlock(b basil.Block, name basil.ID, value interface{}) error {
	return nil
}
