// Code generated by Conflow. DO NOT EDIT.

package directives

import (
	"fmt"

	"github.com/conflowio/conflow/pkg/conflow"
	"github.com/conflowio/conflow/pkg/conflow/annotations"
	"github.com/conflowio/conflow/pkg/conflow/bind"
	"github.com/conflowio/conflow/pkg/schema"
	"github.com/conflowio/conflow/pkg/values"
)

func init() {
	schema.Register(&schema.Object{
		Metadata: schema.Metadata{
			Annotations: map[string]string{
				annotations.EvalStage: "parse",
				annotations.Type:      "directive",
			},
			ID: "github.com/conflowio/conflow/pkg/directives.Number",
		},
		FieldNames:     map[string]string{"$id": "ID", "const": "Const", "default": "Default", "deprecated": "Deprecated", "description": "Description", "enum": "Enum", "examples": "Examples", "exclusiveMaximum": "ExclusiveMaximum", "exclusiveMinimum": "ExclusiveMinimum", "maximum": "Maximum", "minimum": "Minimum", "multipleOf": "MultipleOf", "nullable": "Nullable", "readOnly": "ReadOnly", "title": "Title", "writeOnly": "WriteOnly", "x-annotations": "Annotations"},
		ParameterNames: map[string]string{"$id": "id", "exclusiveMaximum": "exclusive_maximum", "exclusiveMinimum": "exclusive_minimum", "multipleOf": "multiple_of", "readOnly": "read_only", "writeOnly": "write_only", "x-annotations": "annotations"},
		Properties: map[string]schema.Schema{
			"$id": &schema.String{},
			"const": &schema.Number{
				Nullable: true,
			},
			"default": &schema.Number{
				Nullable: true,
			},
			"deprecated":  &schema.Boolean{},
			"description": &schema.String{},
			"enum": &schema.Array{
				Items: &schema.Number{},
			},
			"examples": &schema.Array{
				Items: &schema.Any{},
			},
			"exclusiveMaximum": &schema.Number{
				Nullable: true,
			},
			"exclusiveMinimum": &schema.Number{
				Nullable: true,
			},
			"maximum": &schema.Number{
				Nullable: true,
			},
			"minimum": &schema.Number{
				Nullable: true,
			},
			"multipleOf": &schema.Number{
				Nullable: true,
			},
			"nullable":  &schema.Boolean{},
			"readOnly":  &schema.Boolean{},
			"title":     &schema.String{},
			"writeOnly": &schema.Boolean{},
			"x-annotations": &schema.Map{
				AdditionalProperties: &schema.String{},
			},
		},
	})
}

// NewNumberWithDefaults creates a new Number instance with default values
func NewNumberWithDefaults() *Number {
	b := &Number{}
	return b
}

// NumberInterpreter is the Conflow interpreter for the Number block
type NumberInterpreter struct {
}

func (i NumberInterpreter) Schema() schema.Schema {
	s, _ := schema.Get("github.com/conflowio/conflow/pkg/directives.Number")
	return s
}

// Create creates a new Number block
func (i NumberInterpreter) CreateBlock(id conflow.ID, blockCtx *conflow.BlockContext) conflow.Block {
	b := NewNumberWithDefaults()
	return b
}

// ValueParamName returns the name of the parameter marked as value field, if there is one set
func (i NumberInterpreter) ValueParamName() conflow.ID {
	return ""
}

// ParseContext returns with the parse context for the block
func (i NumberInterpreter) ParseContext(ctx *conflow.ParseContext) *conflow.ParseContext {
	var nilBlock *Number
	if b, ok := conflow.Block(nilBlock).(conflow.ParseContextOverrider); ok {
		return ctx.New(b.ParseContextOverride())
	}

	return ctx
}

func (i NumberInterpreter) Param(b conflow.Block, name conflow.ID) interface{} {
	switch name {
	case "id":
		return b.(*Number).ID
	case "const":
		return b.(*Number).Const
	case "default":
		return b.(*Number).Default
	case "deprecated":
		return b.(*Number).Deprecated
	case "description":
		return b.(*Number).Description
	case "enum":
		return b.(*Number).Enum
	case "examples":
		return b.(*Number).Examples
	case "exclusive_maximum":
		return b.(*Number).ExclusiveMaximum
	case "exclusive_minimum":
		return b.(*Number).ExclusiveMinimum
	case "maximum":
		return b.(*Number).Maximum
	case "minimum":
		return b.(*Number).Minimum
	case "multiple_of":
		return b.(*Number).MultipleOf
	case "nullable":
		return b.(*Number).Nullable
	case "read_only":
		return b.(*Number).ReadOnly
	case "title":
		return b.(*Number).Title
	case "write_only":
		return b.(*Number).WriteOnly
	case "annotations":
		return b.(*Number).Annotations
	default:
		panic(fmt.Errorf("unexpected parameter %q in Number", name))
	}
}

func (i NumberInterpreter) SetParam(block conflow.Block, name conflow.ID, value interface{}) error {
	b := block.(*Number)
	switch name {
	case "id":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("id")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.ID = schema.Value[string](bound)
	case "const":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("const")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.Const = schema.PointerValue[float64](bound)
	case "default":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("default")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.Default = schema.PointerValue[float64](bound)
	case "deprecated":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("deprecated")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.Deprecated = schema.Value[bool](bound)
	case "description":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("description")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.Description = schema.Value[string](bound)
	case "enum":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("enum")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		slice, err := values.AsInterfaceSlice(bound)
		if err != nil {
			return err
		}
		b.Enum = make([]float64, len(slice))
		for slicek, slicev := range slice {
			b.Enum[slicek] = schema.Value[float64](slicev)
		}
	case "examples":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("examples")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		slice, err := values.AsInterfaceSlice(bound)
		if err != nil {
			return err
		}
		b.Examples = slice

	case "exclusive_maximum":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("exclusive_maximum")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.ExclusiveMaximum = schema.PointerValue[float64](bound)
	case "exclusive_minimum":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("exclusive_minimum")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.ExclusiveMinimum = schema.PointerValue[float64](bound)
	case "maximum":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("maximum")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.Maximum = schema.PointerValue[float64](bound)
	case "minimum":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("minimum")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.Minimum = schema.PointerValue[float64](bound)
	case "multiple_of":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("multiple_of")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.MultipleOf = schema.PointerValue[float64](bound)
	case "nullable":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("nullable")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.Nullable = schema.Value[bool](bound)
	case "read_only":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("read_only")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.ReadOnly = schema.Value[bool](bound)
	case "title":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("title")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.Title = schema.Value[string](bound)
	case "write_only":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("write_only")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.WriteOnly = schema.Value[bool](bound)
	case "annotations":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("annotations")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		goMap, err := values.AsStringInterfaceMap(bound)
		if err != nil {
			return err
		}
		b.Annotations = make(map[string]string, len(goMap))
		for goMapk, goMapv := range goMap {
			b.Annotations[goMapk] = schema.Value[string](goMapv)
		}
	}
	return nil
}

func (i NumberInterpreter) SetBlock(block conflow.Block, name conflow.ID, key string, value interface{}) error {
	return nil
}
