// Code generated by Conflow. DO NOT EDIT.

package directives

import (
	"fmt"
	"github.com/conflowio/conflow/conflow"
	"github.com/conflowio/conflow/conflow/schema"
)

// MaxLengthInterpreter is the conflow interpreter for the MaxLength block
type MaxLengthInterpreter struct {
	s schema.Schema
}

func (i MaxLengthInterpreter) Schema() schema.Schema {
	if i.s == nil {
		i.s = &schema.Object{
			Name: "MaxLength",
			Parameters: map[string]schema.Schema{
				"id": &schema.String{
					Metadata: schema.Metadata{
						Annotations: map[string]string{"block.conflow.io/id": "true"},
						ReadOnly:    true,
					},
					Format: "conflow.ID",
				},
				"value": &schema.Integer{
					Metadata: schema.Metadata{
						Annotations: map[string]string{"block.conflow.io/value": "true"},
					},
				},
			},
			Required: []string{"value"},
		}
	}
	return i.s
}

// Create creates a new MaxLength block
func (i MaxLengthInterpreter) CreateBlock(id conflow.ID, blockCtx *conflow.BlockContext) conflow.Block {
	return &MaxLength{
		id: id,
	}
}

// ValueParamName returns the name of the parameter marked as value field, if there is one set
func (i MaxLengthInterpreter) ValueParamName() conflow.ID {
	return "value"
}

// ParseContext returns with the parse context for the block
func (i MaxLengthInterpreter) ParseContext(ctx *conflow.ParseContext) *conflow.ParseContext {
	var nilBlock *MaxLength
	if b, ok := conflow.Block(nilBlock).(conflow.ParseContextOverrider); ok {
		return ctx.New(b.ParseContextOverride())
	}

	return ctx
}

func (i MaxLengthInterpreter) Param(b conflow.Block, name conflow.ID) interface{} {
	switch name {
	case "id":
		return b.(*MaxLength).id
	case "value":
		return b.(*MaxLength).value
	default:
		panic(fmt.Errorf("unexpected parameter %q in MaxLength", name))
	}
}

func (i MaxLengthInterpreter) SetParam(block conflow.Block, name conflow.ID, value interface{}) error {
	b := block.(*MaxLength)
	switch name {
	case "value":
		b.value = value.(int64)
	}
	return nil
}

func (i MaxLengthInterpreter) SetBlock(block conflow.Block, name conflow.ID, value interface{}) error {
	return nil
}
