// Code generated by Basil. DO NOT EDIT.
package fixtures

import (
	"fmt"

	"github.com/opsidian/basil/basil"
	"github.com/opsidian/basil/variable"
	"github.com/opsidian/parsley/parsley"
)

type BlockValueRequiredInterpreter struct{}

// Create creates a new BlockValueRequired block
func (i BlockValueRequiredInterpreter) Create(ctx *basil.EvalContext, node basil.BlockNode) basil.Block {
	return &BlockValueRequired{
		IDField: node.ID(),
	}
}

// Params returns with the list of valid parameters
func (i BlockValueRequiredInterpreter) Params() map[basil.ID]string {
	return map[basil.ID]string{
		"value": "interface{}",
	}
}

// RequiredParams returns with the list of required parameters
func (i BlockValueRequiredInterpreter) RequiredParams() map[basil.ID]bool {
	return map[basil.ID]bool{
		"value": false,
	}
}

// HasForeignID returns true if the block ID is referencing an other block id
func (i BlockValueRequiredInterpreter) HasForeignID() bool {
	return false
}

// HasShortFormat returns true if the block can be defined in the short block format
func (i BlockValueRequiredInterpreter) ValueParamName() basil.ID {
	return "value"
}

// ParseContext returns with the parse context for the block
func (i BlockValueRequiredInterpreter) ParseContext(parentCtx *basil.ParseContext) *basil.ParseContext {
	var nilBlock *BlockValueRequired
	if b, ok := basil.Block(nilBlock).(basil.ParseContextAware); ok {
		return b.ParseContext(parentCtx)
	}

	return parentCtx
}

func (i BlockValueRequiredInterpreter) Param(block basil.Block, name basil.ID) interface{} {
	b := block.(*BlockValueRequired)

	switch name {
	case "id":
		return b.IDField
	case "value":
		return b.Value
	default:
		panic(fmt.Errorf("unexpected parameter %q in BlockValueRequired", name))
	}
}

func (i BlockValueRequiredInterpreter) SetParam(ctx *basil.EvalContext, block basil.Block, name basil.ID, node parsley.Node) parsley.Error {
	b := block.(*BlockValueRequired)

	switch name {
	case "id":
		var err parsley.Error
		b.IDField, err = variable.NodeIdentifierValue(node, ctx)
		return err
	case "value":
		var err parsley.Error
		b.Value, err = variable.NodeAnyValue(node, ctx)
		return err
	default:
		panic(fmt.Errorf("unexpected parameter or block %q in BlockValueRequired", name))
	}
}
