// Code generated by Basil. DO NOT EDIT.
package fixtures

import (
	"fmt"

	"github.com/opsidian/basil/basil"
	"github.com/opsidian/basil/variable"
	"github.com/opsidian/parsley/parsley"
)

type BlockWithReferenceInterpreter struct{}

// Create creates a new BlockWithReference block
func (i BlockWithReferenceInterpreter) Create(ctx *basil.EvalContext, node basil.BlockNode) basil.Block {
	return &BlockWithReference{
		IDField: node.ID(),
	}
}

// Params returns with the list of valid parameters
func (i BlockWithReferenceInterpreter) Params() map[basil.ID]string {
	return nil
}

// RequiredParams returns with the list of required parameters
func (i BlockWithReferenceInterpreter) RequiredParams() map[basil.ID]bool {
	return nil
}

// HasForeignID returns true if the block ID is referencing an other block id
func (i BlockWithReferenceInterpreter) HasForeignID() bool {
	return true
}

// HasShortFormat returns true if the block can be defined in the short block format
func (i BlockWithReferenceInterpreter) ValueParamName() basil.ID {
	return ""
}

// ParseContext returns with the parse context for the block
func (i BlockWithReferenceInterpreter) ParseContext(parentCtx *basil.ParseContext) *basil.ParseContext {
	var nilBlock *BlockWithReference
	if b, ok := basil.Block(nilBlock).(basil.ParseContextAware); ok {
		return b.ParseContext(parentCtx)
	}

	return parentCtx
}

func (i BlockWithReferenceInterpreter) Param(block basil.Block, name basil.ID) interface{} {
	b := block.(*BlockWithReference)

	switch name {
	case "id":
		return b.IDField
	default:
		panic(fmt.Errorf("unexpected parameter %q in BlockWithReference", name))
	}
}

func (i BlockWithReferenceInterpreter) SetParam(ctx *basil.EvalContext, block basil.Block, name basil.ID, node parsley.Node) parsley.Error {
	b := block.(*BlockWithReference)

	switch name {
	case "id":
		var err parsley.Error
		b.IDField, err = variable.NodeIdentifierValue(node, ctx)
		return err
	default:
		panic(fmt.Errorf("unexpected parameter or block %q in BlockWithReference", name))
	}
}
