// Code generated by Conflow. DO NOT EDIT.

package interpreters

import (
	"fmt"

	"github.com/conflowio/conflow/pkg/conflow"
	"github.com/conflowio/conflow/pkg/conflow/bind"
	"github.com/conflowio/conflow/pkg/schema"
	"github.com/conflowio/conflow/pkg/values"
)

// ArrayInterpreter is the Conflow interpreter for the Array block
type ArrayInterpreter struct {
}

func (i ArrayInterpreter) Schema() schema.Schema {
	s, _ := schema.Get("github.com/conflowio/conflow/pkg/schema.Array")
	return s
}

// Create creates a new Array block
func (i ArrayInterpreter) CreateBlock(id conflow.ID, blockCtx *conflow.BlockContext) conflow.Block {
	b := schema.NewArrayWithDefaults()
	return b
}

// ValueParamName returns the name of the parameter marked as value field, if there is one set
func (i ArrayInterpreter) ValueParamName() conflow.ID {
	return ""
}

// ParseContext returns with the parse context for the block
func (i ArrayInterpreter) ParseContext(ctx *conflow.ParseContext) *conflow.ParseContext {
	var nilBlock *schema.Array
	if b, ok := conflow.Block(nilBlock).(conflow.ParseContextOverrider); ok {
		return ctx.New(b.ParseContextOverride())
	}

	return ctx
}

func (i ArrayInterpreter) Param(b conflow.Block, name conflow.ID) interface{} {
	switch name {
	case "id":
		return b.(*schema.Array).ID
	case "const":
		return b.(*schema.Array).Const
	case "default":
		return b.(*schema.Array).Default
	case "deprecated":
		return b.(*schema.Array).Deprecated
	case "description":
		return b.(*schema.Array).Description
	case "enum":
		return b.(*schema.Array).Enum
	case "examples":
		return b.(*schema.Array).Examples
	case "max_items":
		return b.(*schema.Array).MaxItems
	case "min_items":
		return b.(*schema.Array).MinItems
	case "read_only":
		return b.(*schema.Array).ReadOnly
	case "title":
		return b.(*schema.Array).Title
	case "unique_items":
		return b.(*schema.Array).UniqueItems
	case "write_only":
		return b.(*schema.Array).WriteOnly
	case "annotations":
		return b.(*schema.Array).Annotations
	default:
		panic(fmt.Errorf("unexpected parameter %q in Array", name))
	}
}

func (i ArrayInterpreter) SetParam(block conflow.Block, name conflow.ID, value interface{}) error {
	b := block.(*schema.Array)
	switch name {
	case "id":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("id")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.ID = schema.Value[string](bound)
	case "const":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("const")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		slice, err := values.AsInterfaceSlice(bound)
		if err != nil {
			return err
		}
		b.Const = slice

	case "default":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("default")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		slice, err := values.AsInterfaceSlice(bound)
		if err != nil {
			return err
		}
		b.Default = slice

	case "deprecated":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("deprecated")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.Deprecated = schema.Value[bool](bound)
	case "description":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("description")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.Description = schema.Value[string](bound)
	case "enum":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("enum")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		slice, err := values.AsInterfaceSlice(bound)
		if err != nil {
			return err
		}
		b.Enum = make([][]interface{}, len(slice))
		for slicek, slicev := range slice {
			b.Enum[slicek] = slicev.([]interface{})
		}
	case "examples":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("examples")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		slice, err := values.AsInterfaceSlice(bound)
		if err != nil {
			return err
		}
		b.Examples = slice

	case "max_items":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("max_items")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.MaxItems = schema.PointerValue[int64](bound)
	case "min_items":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("min_items")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.MinItems = schema.Value[int64](bound)
	case "read_only":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("read_only")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.ReadOnly = schema.Value[bool](bound)
	case "title":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("title")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.Title = schema.Value[string](bound)
	case "unique_items":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("unique_items")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.UniqueItems = schema.Value[bool](bound)
	case "write_only":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("write_only")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		b.WriteOnly = schema.Value[bool](bound)
	case "annotations":
		propSchema, _ := i.Schema().(*schema.Object).PropertyByParameterName("annotations")
		bound, err := bind.BindValue(propSchema, value)
		if err != nil {
			return err
		}
		goMap, err := values.AsStringInterfaceMap(bound)
		if err != nil {
			return err
		}
		b.Annotations = make(map[string]string, len(goMap))
		for goMapk, goMapv := range goMap {
			b.Annotations[goMapk] = schema.Value[string](goMapv)
		}
	}
	return nil
}

func (i ArrayInterpreter) SetBlock(block conflow.Block, name conflow.ID, key string, value interface{}) error {
	b := block.(*schema.Array)
	switch name {
	case "items":
		b.Items = value.(schema.Schema)
	}
	return nil
}
